apiVersion: email.example.com/v1
kind: Email
metadata:
  labels:
    app.kubernetes.io/name: email-operator
    app.kubernetes.io/managed-by: kustomize
  name: email-sample
spec:
 senderConfigRef: "emailsenderconfig-sample"
 recipientEmail: "it.bootcamp.drive2@gmail.com"
 subject: "Test subject!"
 body: "Hey Milan!"
