apiVersion: email.example.com/v1
kind: Email
metadata:
  labels:
    app.kubernetes.io/name: email-operator
    app.kubernetes.io/managed-by: kustomize
  name: email-sample
spec:
  # TODO(user): Add fields here
