name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    env:
      GO_VERSION: "1.21"
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          TAG=$(git describe)
          MAJOR=$(echo $TAG | cut -d'.' -f1)
          MINOR=$(echo $TAG | cut -d'.' -f2 | cut -d'-' -f1)
          COMMIT_COUNT=$(echo $TAG | cut -d'-' -f2)
          make docker-build docker-push IMG=jovmilan95/email-operator:$MAJOR.$MINOR.$COMMIT_COUNT
