name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'Bump Helm chart version')"
    env:
      go_version: "1.21"
      repository: "jovmilan95/email-operator"
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go_version }}
        id: go

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: make docker-build docker-push IMG=${{ env.repository }}:latest
